//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.DAS.EmployerIncentives.Functions.PaymentsProcess.AcceptanceTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LearnerMatchApiResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LearnerMatchApiResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFA.DAS.EmployerIncentives.Functions.PaymentsProcess.AcceptanceTests.LearnerMatch" +
                            "ApiResponses", typeof(LearnerMatchApiResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;StartDate&quot;: &quot;2020-10-10T00:00:00+00:00&quot;,
        ///    &quot;EventTime&quot;: &quot;0001-01-01T00:00:00+00:00&quot;,
        ///    &quot;IlrSubmissionDate&quot;: &quot;2020-11-09T17:04:31.407+00:00&quot;,
        ///    &quot;IlrSubmissionWindowPeriod&quot;: 3,
        ///    &quot;AcademicYear&quot;: 2021,
        ///    &quot;Ukprn&quot;: 10000028,
        ///    &quot;Uln&quot;: 9900084402,
        ///    &quot;Training&quot;: [
        ///        {
        ///            &quot;Reference&quot;: &quot;ZPROG001&quot;,
        ///            &quot;ProgrammeType&quot;: 25,
        ///            &quot;StandardCode&quot;: 61,
        ///            &quot;FrameworkCode&quot;: 0,
        ///            &quot;PathwayCode&quot;: 0,
        ///            &quot;FundingLineType&quot;: null,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AcrossYear_R03_InLearning {
            get {
                return ResourceManager.GetString("AcrossYear-R03-InLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;StartDate&quot;: &quot;2020-10-10T00:00:00+00:00&quot;,
        ///    &quot;EventTime&quot;: &quot;0001-01-01T00:00:00+00:00&quot;,
        ///    &quot;IlrSubmissionDate&quot;: &quot;2020-11-09T17:55:46.1+00:00&quot;,
        ///    &quot;IlrSubmissionWindowPeriod&quot;: 4,
        ///    &quot;AcademicYear&quot;: 2021,
        ///    &quot;Ukprn&quot;: 10000028,
        ///    &quot;Uln&quot;: 9900084402,
        ///    &quot;Training&quot;: [
        ///        {
        ///            &quot;Reference&quot;: &quot;ZPROG001&quot;,
        ///            &quot;ProgrammeType&quot;: 25,
        ///            &quot;StandardCode&quot;: 61,
        ///            &quot;FrameworkCode&quot;: 0,
        ///            &quot;PathwayCode&quot;: 0,
        ///            &quot;FundingLineType&quot;: null,
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AcrossYear_R04_InLearning {
            get {
                return ResourceManager.GetString("AcrossYear-R04-InLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;StartDate&quot;: &quot;2020-08-10T00:00:00+00:00&quot;,
        ///    &quot;EventTime&quot;: &quot;0001-01-01T00:00:00+00:00&quot;,
        ///    &quot;IlrSubmissionDate&quot;: &quot;2020-11-09T17:58:57.863+00:00&quot;,
        ///    &quot;IlrSubmissionWindowPeriod&quot;: 4,
        ///    &quot;AcademicYear&quot;: 2021,
        ///    &quot;Ukprn&quot;: 10036143,
        ///    &quot;Uln&quot;: 9900084607,
        ///    &quot;Training&quot;: [
        ///        {
        ///            &quot;Reference&quot;: &quot;ZPROG001&quot;,
        ///            &quot;ProgrammeType&quot;: 25,
        ///            &quot;StandardCode&quot;: 61,
        ///            &quot;FrameworkCode&quot;: 0,
        ///            &quot;PathwayCode&quot;: 0,
        ///            &quot;FundingLineType&quot;: null,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BL_R03_InBreak {
            get {
                return ResourceManager.GetString("BL-R03-InBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;StartDate&quot;: &quot;2020-08-10T00:00:00+00:00&quot;,
        ///    &quot;EventTime&quot;: &quot;0001-01-01T00:00:00+00:00&quot;,
        ///    &quot;IlrSubmissionDate&quot;: &quot;2020-11-09T16:53:17.293+00:00&quot;,
        ///    &quot;IlrSubmissionWindowPeriod&quot;: 3,
        ///    &quot;AcademicYear&quot;: 2021,
        ///    &quot;Ukprn&quot;: 10036143,
        ///    &quot;Uln&quot;: 9900084607,
        ///    &quot;Training&quot;: [
        ///        {
        ///            &quot;Reference&quot;: &quot;ZPROG001&quot;,
        ///            &quot;ProgrammeType&quot;: 25,
        ///            &quot;StandardCode&quot;: 61,
        ///            &quot;FrameworkCode&quot;: 0,
        ///            &quot;PathwayCode&quot;: 0,
        ///            &quot;FundingLineType&quot;: null,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BL_R03_InLearning {
            get {
                return ResourceManager.GetString("BL-R03-InLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;StartDate&quot;: &quot;2020-08-10T00:00:00+00:00&quot;,
        ///    &quot;EventTime&quot;: &quot;0001-01-01T00:00:00+00:00&quot;,
        ///    &quot;IlrSubmissionDate&quot;: &quot;2020-11-09T16:53:17.293+00:00&quot;,
        ///    &quot;IlrSubmissionWindowPeriod&quot;: 3,
        ///    &quot;AcademicYear&quot;: 2021,
        ///    &quot;Ukprn&quot;: 10036143,
        ///    &quot;Uln&quot;: 9900084607,
        ///    &quot;Training&quot;: [
        ///        {
        ///            &quot;Reference&quot;: &quot;ZPROG001&quot;,
        ///            &quot;ProgrammeType&quot;: 25,
        ///            &quot;StandardCode&quot;: 61,
        ///            &quot;FrameworkCode&quot;: 0,
        ///            &quot;PathwayCode&quot;: 0,
        ///            &quot;FundingLineType&quot;: null,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BL_R03_InLearning_DifferentApprenticeship {
            get {
                return ResourceManager.GetString("BL-R03-InLearning-DifferentApprenticeship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;StartDate&quot;: &quot;2020-08-10T00:00:00+00:00&quot;,
        ///    &quot;EventTime&quot;: &quot;0001-01-01T00:00:00+00:00&quot;,
        ///    &quot;IlrSubmissionDate&quot;: &quot;2020-11-09T16:53:17.293+00:00&quot;,
        ///    &quot;IlrSubmissionWindowPeriod&quot;: 3,
        ///    &quot;AcademicYear&quot;: 2021,
        ///    &quot;Ukprn&quot;: 10036143,
        ///    &quot;Uln&quot;: 9900084607,
        ///    &quot;Training&quot;: [
        ///        {
        ///            &quot;Reference&quot;: &quot;ZPROG001&quot;,
        ///            &quot;ProgrammeType&quot;: 25,
        ///            &quot;StandardCode&quot;: 61,
        ///            &quot;FrameworkCode&quot;: 0,
        ///            &quot;PathwayCode&quot;: 0,
        ///            &quot;FundingLineType&quot;: null,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BL_R03_InLearning_NoEndDate {
            get {
                return ResourceManager.GetString("BL-R03-InLearning-NoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;StartDate&quot;: &quot;2020-08-10T00:00:00+00:00&quot;,
        ///    &quot;EventTime&quot;: &quot;0001-01-01T00:00:00+00:00&quot;,
        ///    &quot;IlrSubmissionDate&quot;: &quot;2020-11-09T16:53:17.293+00:00&quot;,
        ///    &quot;IlrSubmissionWindowPeriod&quot;: 3,
        ///    &quot;AcademicYear&quot;: 2021,
        ///    &quot;Ukprn&quot;: 10036143,
        ///    &quot;Uln&quot;: 9900084607,
        ///    &quot;Training&quot;: [
        ///        {
        ///            &quot;Reference&quot;: &quot;ZPROG001&quot;,
        ///            &quot;ProgrammeType&quot;: 25,
        ///            &quot;StandardCode&quot;: 61,
        ///            &quot;FrameworkCode&quot;: 0,
        ///            &quot;PathwayCode&quot;: 0,
        ///            &quot;FundingLineType&quot;: null,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BL_R03_InLearning_NoPayable {
            get {
                return ResourceManager.GetString("BL-R03-InLearning-NoPayable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;StartDate&quot;: &quot;2020-08-10T00:00:00+00:00&quot;,
        ///    &quot;EventTime&quot;: &quot;0001-01-01T00:00:00+00:00&quot;,
        ///    &quot;IlrSubmissionDate&quot;: &quot;2020-11-09T16:53:17.293+00:00&quot;,
        ///    &quot;IlrSubmissionWindowPeriod&quot;: 3,
        ///    &quot;AcademicYear&quot;: 2021,
        ///    &quot;Ukprn&quot;: 10036143,
        ///    &quot;Uln&quot;: 9900084607,
        ///    &quot;Training&quot;: []
        ///}.
        /// </summary>
        internal static string BL_R03_InLearning_NoTraining {
            get {
                return ResourceManager.GetString("BL-R03-InLearning-NoTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;StartDate&quot;: &quot;2020-08-10T00:00:00+00:00&quot;,
        ///    &quot;EventTime&quot;: &quot;0001-01-01T00:00:00+00:00&quot;,
        ///    &quot;IlrSubmissionDate&quot;: &quot;2020-11-09T16:53:17.293+00:00&quot;,
        ///    &quot;IlrSubmissionWindowPeriod&quot;: 3,
        ///    &quot;AcademicYear&quot;: 2021,
        ///    &quot;Ukprn&quot;: 10036143,
        ///    &quot;Uln&quot;: 9900084607,
        ///    &quot;Training&quot;: [
        ///        {
        ///            &quot;Reference&quot;: &quot;ZPROG002&quot;,
        ///            &quot;ProgrammeType&quot;: 25,
        ///            &quot;StandardCode&quot;: 61,
        ///            &quot;FrameworkCode&quot;: 0,
        ///            &quot;PathwayCode&quot;: 0,
        ///            &quot;FundingLineType&quot;: null,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BL_R03_InLearning_NoZPROG001 {
            get {
                return ResourceManager.GetString("BL-R03-InLearning-NoZPROG001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;StartDate&quot;: &quot;2020-08-10T00:00:00+00:00&quot;,
        ///    &quot;EventTime&quot;: &quot;0001-01-01T00:00:00+00:00&quot;,
        ///    &quot;IlrSubmissionDate&quot;: &quot;2020-11-09T17:58:57.863+00:00&quot;,
        ///    &quot;IlrSubmissionWindowPeriod&quot;: 4,
        ///    &quot;AcademicYear&quot;: 2021,
        ///    &quot;Ukprn&quot;: 10036143,
        ///    &quot;Uln&quot;: 9900084607,
        ///    &quot;Training&quot;: [
        ///        {
        ///            &quot;Reference&quot;: &quot;ZPROG001&quot;,
        ///            &quot;ProgrammeType&quot;: 25,
        ///            &quot;StandardCode&quot;: 61,
        ///            &quot;FrameworkCode&quot;: 0,
        ///            &quot;PathwayCode&quot;: 0,
        ///            &quot;FundingLineType&quot;: null,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BL_R04_InBreak {
            get {
                return ResourceManager.GetString("BL-R04-InBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;StartDate&quot;: &quot;2020-10-10T00:00:00+00:00&quot;,
        ///    &quot;EventTime&quot;: &quot;0001-01-01T00:00:00+00:00&quot;,
        ///    &quot;IlrSubmissionDate&quot;: &quot;2020-11-09T17:55:46.1+00:00&quot;,
        ///    &quot;IlrSubmissionWindowPeriod&quot;: 4,
        ///    &quot;AcademicYear&quot;: 2021,
        ///    &quot;Ukprn&quot;: 10000028,
        ///    &quot;Uln&quot;: 9900084305,
        ///    &quot;Training&quot;: [
        ///        {
        ///            &quot;Reference&quot;: &quot;ZPROG001&quot;,
        ///            &quot;ProgrammeType&quot;: 25,
        ///            &quot;StandardCode&quot;: 61,
        ///            &quot;FrameworkCode&quot;: 0,
        ///            &quot;PathwayCode&quot;: 0,
        ///            &quot;FundingLineType&quot;: null,
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Course_Price_DlcokResoved_R04 {
            get {
                return ResourceManager.GetString("Course-Price-DlcokResoved-R04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;StartDate&quot;: &quot;2020-08-10T00:00:00+00:00&quot;,
        ///    &quot;EventTime&quot;: &quot;0001-01-01T00:00:00+00:00&quot;,
        ///    &quot;IlrSubmissionDate&quot;: &quot;2020-11-09T17:04:31.407+00:00&quot;,
        ///    &quot;IlrSubmissionWindowPeriod&quot;: 3,
        ///    &quot;AcademicYear&quot;: 2021,
        ///    &quot;Ukprn&quot;: 10036143,
        ///    &quot;Uln&quot;: 9900084607,
        ///    &quot;Training&quot;: [
        ///        {
        ///            &quot;Reference&quot;: &quot;ZPROG001&quot;,
        ///            &quot;ProgrammeType&quot;: 25,
        ///            &quot;StandardCode&quot;: 62,
        ///            &quot;FrameworkCode&quot;: 0,
        ///            &quot;PathwayCode&quot;: 0,
        ///            &quot;FundingLineType&quot;: null,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Course_Price_Dlock_R03 {
            get {
                return ResourceManager.GetString("Course-Price-Dlock-R03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;StartDate&quot;: &quot;2020-08-06T00:00:00+00:00&quot;,
        ///    &quot;EventTime&quot;: &quot;0001-01-01T00:00:00+00:00&quot;,
        ///    &quot;IlrSubmissionDate&quot;: &quot;2020-11-09T16:53:17.293+00:00&quot;,
        ///    &quot;IlrSubmissionWindowPeriod&quot;: 3,
        ///    &quot;AcademicYear&quot;: 2021,
        ///    &quot;Ukprn&quot;: 10036143,
        ///    &quot;Uln&quot;: 9900084704,
        ///    &quot;Training&quot;: [
        ///        {
        ///            &quot;Reference&quot;: &quot;ZPROG001&quot;,
        ///            &quot;ProgrammeType&quot;: 25,
        ///            &quot;StandardCode&quot;: 61,
        ///            &quot;FrameworkCode&quot;: 0,
        ///            &quot;PathwayCode&quot;: 0,
        ///            &quot;FundingLineType&quot;: null,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PC_R03_NoDlock {
            get {
                return ResourceManager.GetString("PC-R03-NoDlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;StartDate&quot;: &quot;2020-08-06T00:00:00+00:00&quot;,
        ///    &quot;EventTime&quot;: &quot;0001-01-01T00:00:00+00:00&quot;,
        ///    &quot;IlrSubmissionDate&quot;: &quot;2020-11-09T17:58:57.863+00:00&quot;,
        ///    &quot;IlrSubmissionWindowPeriod&quot;: 4,
        ///    &quot;AcademicYear&quot;: 2021,
        ///    &quot;Ukprn&quot;: 10036143,
        ///    &quot;Uln&quot;: 9900084704,
        ///    &quot;Training&quot;: [
        ///        {
        ///            &quot;Reference&quot;: &quot;ZPROG001&quot;,
        ///            &quot;ProgrammeType&quot;: 25,
        ///            &quot;StandardCode&quot;: 61,
        ///            &quot;FrameworkCode&quot;: 0,
        ///            &quot;PathwayCode&quot;: 0,
        ///            &quot;FundingLineType&quot;: null,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PC_R04_Pricechange_DLock7 {
            get {
                return ResourceManager.GetString("PC-R04-Pricechange-DLock7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;StartDate&quot;: &quot;2020-08-10T00:00:00+00:00&quot;,
        ///    &quot;EventTime&quot;: &quot;0001-01-01T00:00:00+00:00&quot;,
        ///    &quot;IlrSubmissionDate&quot;: &quot;2020-11-09T16:53:17.293+00:00&quot;,
        ///    &quot;IlrSubmissionWindowPeriod&quot;: 3,
        ///    &quot;AcademicYear&quot;: 2021,
        ///    &quot;Ukprn&quot;: 10036143,
        ///    &quot;Uln&quot;: 9900084607,
        ///    &quot;Training&quot;: [
        ///        {
        ///            &quot;Reference&quot;: &quot;ZPROG001&quot;,
        ///            &quot;ProgrammeType&quot;: 25,
        ///            &quot;StandardCode&quot;: 61,
        ///            &quot;FrameworkCode&quot;: 0,
        ///            &quot;PathwayCode&quot;: 0,
        ///            &quot;FundingLineType&quot;: null,
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StartDateChange {
            get {
                return ResourceManager.GetString("StartDateChange", resourceCulture);
            }
        }
    }
}
